### Create billing account with grpc
GRPC localhost:9002/BillingService/CreateBillingAccount
Content-Type: application/json

{

  "patientId": "123e4567-e89b-12d3-a456-426614174000",
  "name": "John Doe",
  "email": "johndoe@gmail.com"
}