spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://patient-service:8081
          predicates:
            - Path=/api/patients/**
          filters:
            - RewritePath=/api/patients/(?<segment>.*), /api/patients/$\{segment}
server:
  port: 8080

eureka:
  client:
    service-url:
        defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
        register-with-eureka: true
        fetch-registry: true
  instance:
    prefer-ip-address: true
