# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-db
  template:
    metadata:
      labels:
        app: auth-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_USER
              value: admin_user
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          emptyDir: {}  # For development; use PVC for production
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-db
spec:
  selector:
    app: auth-service-db
  ports:
    - port: 5432
      targetPort: 5432