### Create patient

POST http://localhost:8081/api/patients
Content-Type: application/json

{
  "name": "John Doe With Billing Account Kafka 1",
  "address": "123 Main",
  "dateOfBirth": "2004-02-10",
  "email": "hello1422@gmail.com"
}

###